pip install requests-cache
pip install pandas
pip install xlrd
pip install PyQt5
pip install google_auth_oauthlib
pip install google-api-python-client
pip install openpyxl
pip install scrapy
pip install xlsxwriter