# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(-1, -1, 201, 501))
        self.left_frame.setStyleSheet("background-color: rgb(80, 0, 0);")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.title_label = QtWidgets.QLabel(self.left_frame)
        self.title_label.setGeometry(QtCore.QRect(10, 20, 181, 41))
        self.title_label.setStyleSheet("font: 25 22pt \"Segoe UI Light\";")
        self.title_label.setObjectName("title_label")
        self.title_line = QtWidgets.QLabel(self.left_frame)
        self.title_line.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.title_line.setObjectName("title_line")
        self.type_group = QtWidgets.QGroupBox(self.left_frame)
        self.type_group.setGeometry(QtCore.QRect(30, 90, 151, 111))
        self.type_group.setStyleSheet("font: 25 10pt \"Segoe UI Light\";\n"
"color:rgb(255,255,255);")
        self.type_group.setObjectName("type_group")
        self.books_radio = QtWidgets.QRadioButton(self.type_group)
        self.books_radio.setGeometry(QtCore.QRect(30, 70, 82, 21))
        self.books_radio.setStyleSheet("font: 25 12pt \"Segoe UI Light\";\n"
"color:rgb(255,255,255);")
        self.books_radio.setObjectName("books_radio")
        self.songs_radio = QtWidgets.QRadioButton(self.type_group)
        self.songs_radio.setGeometry(QtCore.QRect(30, 30, 111, 21))
        self.songs_radio.setStyleSheet("font: 25 12pt \"Segoe UI Light\";\n"
"color:rgb(255,255,255);")
        self.songs_radio.setObjectName("songs_radio")
        self.title_line.raise_()
        self.title_label.raise_()
        self.type_group.raise_()
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(199, -1, 601, 501))
        self.right_frame.setStyleSheet("background-color: rgb(214, 210, 196);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.io_title_label = QtWidgets.QLabel(self.right_frame)
        self.io_title_label.setGeometry(QtCore.QRect(30, 30, 91, 21))
        self.io_title_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.io_title_label.setObjectName("io_title_label")
        self.holine = QtWidgets.QLabel(self.right_frame)
        self.holine.setGeometry(QtCore.QRect(30, 40, 561, 20))
        self.holine.setObjectName("holine")
        self.settings_frame = QtWidgets.QFrame(self.right_frame)
        self.settings_frame.setGeometry(QtCore.QRect(0, 120, 611, 181))
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.attributes_groupBox = QtWidgets.QGroupBox(self.settings_frame)
        self.attributes_groupBox.setGeometry(QtCore.QRect(30, 110, 531, 51))
        self.attributes_groupBox.setObjectName("attributes_groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.attributes_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 511, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attribute_checkBox_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.attribute_checkBox_1.setObjectName("attribute_checkBox_1")
        self.horizontalLayout.addWidget(self.attribute_checkBox_1)
        self.attribute_checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.attribute_checkBox_2.setObjectName("attribute_checkBox_2")
        self.horizontalLayout.addWidget(self.attribute_checkBox_2)
        self.attribute_checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.attribute_checkBox_3.setObjectName("attribute_checkBox_3")
        self.horizontalLayout.addWidget(self.attribute_checkBox_3)
        self.attribute_checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.attribute_checkBox_4.setObjectName("attribute_checkBox_4")
        self.horizontalLayout.addWidget(self.attribute_checkBox_4)
        self.source_groupBox = QtWidgets.QGroupBox(self.settings_frame)
        self.source_groupBox.setGeometry(QtCore.QRect(30, 50, 531, 51))
        self.source_groupBox.setObjectName("source_groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.source_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 511, 20))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.source_checkBox_1 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.source_checkBox_1.setObjectName("source_checkBox_1")
        self.horizontalLayout_2.addWidget(self.source_checkBox_1)
        self.source_checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.source_checkBox_2.setObjectName("source_checkBox_2")
        self.horizontalLayout_2.addWidget(self.source_checkBox_2)
        self.settings_title_label = QtWidgets.QLabel(self.settings_frame)
        self.settings_title_label.setGeometry(QtCore.QRect(30, 10, 91, 21))
        self.settings_title_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.settings_title_label.setObjectName("settings_title_label")
        self.holine2 = QtWidgets.QLabel(self.settings_frame)
        self.holine2.setGeometry(QtCore.QRect(30, 20, 561, 20))
        self.holine2.setObjectName("holine2")
        self.holine2.raise_()
        self.attributes_groupBox.raise_()
        self.source_groupBox.raise_()
        self.settings_title_label.raise_()
        self.input_path_label = QtWidgets.QLabel(self.right_frame)
        self.input_path_label.setGeometry(QtCore.QRect(60, 70, 391, 16))
        self.input_path_label.setObjectName("input_path_label")
        self.browse_input_button = QtWidgets.QPushButton(self.right_frame)
        self.browse_input_button.setGeometry(QtCore.QRect(470, 70, 75, 23))
        self.browse_input_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browse_input_button.setObjectName("browse_input_button")
        self.start_button = QtWidgets.QPushButton(self.right_frame)
        self.start_button.setGeometry(QtCore.QRect(420, 320, 75, 23))
        self.start_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.start_button.setObjectName("start_button")
        self.progressBar = QtWidgets.QProgressBar(self.right_frame)
        self.progressBar.setGeometry(QtCore.QRect(60, 320, 331, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.output_path_label = QtWidgets.QLabel(self.right_frame)
        self.output_path_label.setGeometry(QtCore.QRect(60, 100, 391, 16))
        self.output_path_label.setObjectName("output_path_label")
        self.browse_output_button = QtWidgets.QPushButton(self.right_frame)
        self.browse_output_button.setGeometry(QtCore.QRect(470, 100, 75, 23))
        self.browse_output_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browse_output_button.setObjectName("browse_output_button")
        self.holine.raise_()
        self.io_title_label.raise_()
        self.settings_frame.raise_()
        self.input_path_label.raise_()
        self.browse_input_button.raise_()
        self.start_button.raise_()
        self.progressBar.raise_()
        self.output_path_label.raise_()
        self.browse_output_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Scraper"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Data Scraper</span></p></body></html>"))
        self.title_line.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">_________________</span></p></body></html>"))
        self.type_group.setTitle(_translate("MainWindow", "Type"))
        self.books_radio.setText(_translate("MainWindow", "Books"))
        self.songs_radio.setText(_translate("MainWindow", "Songs"))
        self.io_title_label.setText(_translate("MainWindow", "Input/Output"))
        self.holine.setText(_translate("MainWindow", "__________________________________________________________________________________________"))
        self.attributes_groupBox.setTitle(_translate("MainWindow", "Scraping Attributes"))
        self.attribute_checkBox_1.setText(_translate("MainWindow", "View/Play Count"))
        self.attribute_checkBox_2.setText(_translate("MainWindow", "Duration"))
        self.attribute_checkBox_3.setText(_translate("MainWindow", "Thumbs Up"))
        self.attribute_checkBox_4.setText(_translate("MainWindow", "Thumbs Down"))
        self.source_groupBox.setTitle(_translate("MainWindow", "Scraping Source"))
        self.source_checkBox_1.setText(_translate("MainWindow", "Youtube"))
        self.source_checkBox_2.setText(_translate("MainWindow", "Spotify"))
        self.settings_title_label.setText(_translate("MainWindow", "Settings"))
        self.holine2.setText(_translate("MainWindow", "__________________________________________________________________________________________"))
        self.input_path_label.setText(_translate("MainWindow", "Please select input xlsx file..."))
        self.browse_input_button.setText(_translate("MainWindow", "Browse.."))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.output_path_label.setText(_translate("MainWindow", "Please select output directory..."))
        self.browse_output_button.setText(_translate("MainWindow", "Browse.."))

import ui.qtsrc.resources_rc
